### ISSUE TITLE
What license would this project be under?

### ISSUE THREAD

**Issue by adroit91** [sittim/msp430-OTP#1]
Hi,

This is something I have always wanted to work on (for my own work), but haven't gotten around to.

I would love to contribute, but I'm not sure if I would be able to use it in commercial applications for myself? Not that I wouldn't want to contribute if I can't! :)

Please let me know.

Regards,
Anup

**Comment by sittim** [comment]
The licence is listed in code.  Basically I am not responsible for the outcome of the use of the code otherwise you are free to use it as you wish.

**Comment by adroit91** [comment]
Great! Let me see how to get started with helping out!
